/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Surfaces ──────────────────────────────────────────────────────
        surface:                     'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim':               'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':            'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest':  'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':     'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container':         'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high':    'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'on-surface':                'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':        'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'inverse-surface':           'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':        'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        outline:                     'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':           'rgb(var(--color-outline-variant) / <alpha-value>)',
        'surface-tint':              'rgb(var(--color-surface-tint) / <alpha-value>)',
        'surface-variant':           'rgb(var(--color-surface-variant) / <alpha-value>)',
        // ── Primary ───────────────────────────────────────────────────────
        primary:                     'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':                'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':         'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':      'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'inverse-primary':           'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'primary-fixed':             'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim':         'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed':          'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant':  'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
        // ── Secondary ─────────────────────────────────────────────────────
        secondary:                       'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary':                  'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container':           'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container':        'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'secondary-fixed':               'rgb(var(--color-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim':           'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed':            'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant':    'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',
        // ── Tertiary ──────────────────────────────────────────────────────
        tertiary:                        'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary':                   'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'tertiary-container':            'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container':         'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed':                'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim':            'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed':             'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant':     'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
        // ── Error ─────────────────────────────────────────────────────────
        error:                   'rgb(var(--color-error) / <alpha-value>)',
        'on-error':              'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container':       'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container':    'rgb(var(--color-on-error-container) / <alpha-value>)',
        // ── Background ────────────────────────────────────────────────────
        background:              'rgb(var(--color-background) / <alpha-value>)',
        'on-background':         'rgb(var(--color-on-background) / <alpha-value>)',
        // ── Overlay & input (baked-in alpha — no <alpha-value> modifier) ──
        'overlay-sm': 'var(--color-overlay-sm)',
        'overlay-md': 'var(--color-overlay-md)',
        'overlay-lg': 'var(--color-overlay-lg)',
        'input-bg':   'var(--color-input-bg)',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        'sidebar-width': '260px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md':           ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
